// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementStock = `-- name: DecrementStock :exec
UPDATE products SET stock_quantity = stock_quantity - $2 WHERE id = $1
`

type DecrementStockParams struct {
	ID            pgtype.UUID `json:"id"`
	StockQuantity int32       `json:"stock_quantity"`
}

func (q *Queries) DecrementStock(ctx context.Context, arg DecrementStockParams) error {
	_, err := q.db.Exec(ctx, decrementStock, arg.ID, arg.StockQuantity)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, sku, price, stock_quantity FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Price,
		&i.StockQuantity,
	)
	return i, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
SELECT id, name, sku, price, stock_quantity FROM products WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetProductForUpdate(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductForUpdate, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Price,
		&i.StockQuantity,
	)
	return i, err
}
