// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO stock_reservations (product_id, order_id, quantity, expires_at) VALUES ($1, $2, $3, $4) RETURNING id, product_id, order_id, quantity, status, expires_at, created_at
`

type CreateReservationParams struct {
	ProductID pgtype.UUID        `json:"product_id"`
	OrderID   pgtype.UUID        `json:"order_id"`
	Quantity  int32              `json:"quantity"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (StockReservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.ProductID,
		arg.OrderID,
		arg.Quantity,
		arg.ExpiresAt,
	)
	var i StockReservation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrderID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredReservations = `-- name: DeleteExpiredReservations :many
DELETE FROM stock_reservations WHERE expires_at < now() AND status = 'reserved' RETURNING id, product_id, order_id, quantity, status, expires_at, created_at
`

func (q *Queries) DeleteExpiredReservations(ctx context.Context) ([]StockReservation, error) {
	rows, err := q.db.Query(ctx, deleteExpiredReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockReservation
	for rows.Next() {
		var i StockReservation
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OrderID,
			&i.Quantity,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, product_id, order_id, quantity, status, expires_at, created_at FROM stock_reservations WHERE id = $1
`

func (q *Queries) GetReservationByID(ctx context.Context, id pgtype.UUID) (StockReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i StockReservation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrderID,
		&i.Quantity,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :exec
UPDATE stock_reservations SET status = $2 WHERE id = $1
`

type UpdateReservationStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error {
	_, err := q.db.Exec(ctx, updateReservationStatus, arg.ID, arg.Status)
	return err
}
