# --- Стадия 1: сборка ---
FROM golang:1.26-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/inventory-service ./cmd/server

FROM alpine:3.20

RUN apk add --no-cache ca-certificates wget
RUN adduser -D -g '' appuser

WORKDIR /app
COPY --from=builder /app/bin/inventory-service .

USER appuser

EXPOSE 50051

ENTRYPOINT ["./inventory-service"]
