// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID        pgtype.UUID        `json:"id"`
	OrderID   pgtype.UUID        `json:"order_id"`
	Amount    pgtype.Numeric     `json:"amount"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
